repos:
-   repo: git://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.12
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
    -   id: forbid-tabs
        exclude: tests/resources/main.*_with_license.cpp
    -   id: remove-tabs
        exclude: tests/resources/main.*_with_license.cpp
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        files: ''
        exclude: tests/resources/main.*_with_license.cpp
    -   id: check-yaml
-   repo: git://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a4
    hooks:
    -   id: pylint
        args:
        - --rcfile=.pylintrc
        - --reports=no
        exclude: ^tests/resources/.*(init_with_license\.py|todo).*$
-   repo: local
    hooks:
    -   id: py.test
        name: py.test
        language: python
        additional_dependencies: ['pytest', 'pytest-cov', 'coverage', 'fuzzywuzzy', 'python-Levenshtein-wheels']
        entry: sh
        require_serial: true
        pass_filenames: false
        files: '\.py$'
